import React from 'react';
import { ATSAnalysis, Language } from '../types';
import { UI_TEXTS } from '../constants';
import { 
  Printer, Briefcase, Award, TrendingUp, 
  BookOpen, UserCheck, Target, Layers, Image, Zap
} from 'lucide-react';
import { ScoreGauge, CategoryBreakdown } from './AnalysisCharts';
import html2canvas from 'html2canvas';

interface VocationalReportProps {
  analysis: ATSAnalysis;
  lang: Language;
}

export const VocationalReport: React.FC<VocationalReportProps> = ({ analysis, lang }) => {
  const t = UI_TEXTS[lang];

  const handlePrint = () => {
    window.print();
  };

  const handleExportPng = async () => {
    const element = document.getElementById('vocational-report');
    if (element) {
        try {
            const canvas = await html2canvas(element, { scale: 2, backgroundColor: '#ffffff', useCORS: true });
            const link = document.createElement('a');
            link.download = `Reporte_Vocacional_${new Date().toISOString().slice(0,10)}.png`;
            link.href = canvas.toDataURL();
            link.click();
        } catch (err) {
            console.error("Failed to export PNG", err);
        }
    }
  };

  const getStatusColor = (score: number) => {
    if (score >= 85) return 'bg-accent';
    if (score >= 70) return 'bg-primary';
    if (score >= 50) return 'bg-amber-500';
    return 'bg-secondary';
  };

  const getStatusLabel = (score: number) => {
    if (lang === 'en') {
        if (score >= 85) return 'Excellent';
        if (score >= 70) return 'Good';
        if (score >= 50) return 'Average';
        return 'Critical';
    }
    if (score >= 85) return 'Excelente';
    if (score >= 70) return 'Bueno';
    if (score >= 50) return 'Mejorable';
    return 'Crítico';
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-700">
      
      {/* ACTION BAR */}
      <div className="flex justify-between items-center bg-white p-6 rounded-card shadow-vibrant border border-white no-print">
        <h2 className="text-xl font-black text-primary flex items-center gap-3">
           <div className="bg-indigo-50 p-2 rounded-xl"><Layers className="text-primary"/></div> 
           {lang === 'en' ? 'Vocational Neural Report' : 'Informe Vocacional Neural'}
        </h2>
        <div className="flex gap-3">
           <button 
             onClick={handleExportPng}
             className="flex items-center gap-2 px-5 py-3 bg-indigo-50 text-primary rounded-pill text-xs font-black uppercase tracking-widest hover:bg-indigo-100 transition-all"
           >
             <Image size={18}/> {t.exportPng}
           </button>
           <button 
             onClick={handlePrint}
             className="flex items-center gap-2 px-5 py-3 bg-primary text-white rounded-pill text-xs font-black uppercase tracking-widest hover:bg-indigo-700 transition-all hover:scale-105 shadow-vibrant"
           >
             <Printer size={18}/> {t.printPdf}
           </button>
        </div>
      </div>

      {/* REPORT CONTAINER - PRINTABLE AREA */}
      <div id="vocational-report" className="bg-white p-12 rounded-container shadow-vibrant border border-white print:shadow-none print:border-none print:p-0 relative overflow-hidden">
         <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-primary via-secondary to-accent"></div>
         
         {/* HEADER */}
         <div className="flex flex-col md:flex-row justify-between items-start md:items-center border-b border-indigo-50 pb-10 mb-10">
            <div>
               <div className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-50 text-primary rounded-pill text-[10px] font-black uppercase tracking-widest mb-4 border border-indigo-100">
                 <UserCheck size={14}/> {t.neuralAnalysis}
               </div>
               <h1 className="text-4xl font-black text-text-main tracking-tighter leading-tight">{lang === 'en' ? 'Professional Profile Audit' : 'Perfil Profesional Auditado'}</h1>
               <p className="text-text-muted font-bold uppercase tracking-widest text-xs mt-2">Generated by ATS Master Pro • {new Date().toLocaleDateString()}</p>
            </div>
            <div className="mt-8 md:mt-0 flex items-center gap-8">
                <div className="text-right">
                    <p className="text-[10px] font-black text-text-muted uppercase tracking-[0.2em] mb-1">{t.globalScore}</p>
                    <p className="text-5xl font-black text-primary tracking-tighter">{analysis.overallScore}<span className="text-2xl text-text-muted">/100</span></p>
                </div>
                <div className="h-24 w-24">
                   <ScoreGauge score={analysis.overallScore} label={t.atsScore} />
                </div>
            </div>
         </div>

         {/* SECTION 1: DETAILED SCORING */}
         <div className="mb-12">
            <h3 className="text-xs font-black text-text-muted uppercase tracking-[0.3em] mb-8 flex items-center gap-3">
               <Target size={20} className="text-primary"/> {t.sectionScore}
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="p-8 bg-white rounded-card border-2 border-indigo-50 shadow-sm">
                    <CategoryBreakdown data={analysis} lang={lang} />
                </div>
                <div className="grid grid-cols-1 gap-4">
                  {analysis.sectionBreakdown?.slice(0, 4).map((section, idx) => (
                      <div key={idx} className="bg-indigo-50/30 p-4 rounded-card border border-indigo-50 flex justify-between items-center group hover:border-primary transition-all">
                          <div>
                            <span className="text-[10px] font-black text-text-muted uppercase tracking-widest block mb-1">{section.category}</span>
                            <p className="text-xs font-bold text-text-main">{section.feedback}</p>
                          </div>
                          <span className={`text-xl font-black tracking-tighter ${getStatusColor(section.score).replace('bg-', 'text-')}`}>
                             {section.score}%
                          </span>
                      </div>
                  ))}
                </div>
            </div>
         </div>

         {/* SECTION 2: VOCATIONAL PROFILE */}
         <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-10">
             {/* SENIORITY & VALUE */}
             <div className="md:col-span-1 space-y-6">
                 <div className="bg-text-main text-white p-8 rounded-card relative overflow-hidden shadow-vibrant">
                     <div className="absolute top-0 right-0 p-4 opacity-5 translate-x-1/4 -translate-y-1/4 scale-150"><Award size={120}/></div>
                     <p className="text-[10px] font-black text-indigo-300 uppercase tracking-[0.2em] mb-2">{t.detectedSeniority}</p>
                     <p className="text-3xl font-black text-white mb-6 uppercase tracking-tight">{analysis.vocationalProfile?.estimatedSeniority || "N/A"}</p>
                     
                     <p className="text-[10px] font-black text-indigo-300 uppercase tracking-[0.2em] mb-3">{t.marketValue}</p>
                     <div className="flex items-center gap-4 bg-white/10 p-4 rounded-2xl border border-white/10">
                        <div className="flex-1 bg-white/20 h-2 rounded-pill overflow-hidden">
                           <div className="bg-accent h-full" style={{width: `${analysis.vocationalProfile?.marketValueScore || 0}%`}}></div>
                        </div>
                        <span className="text-lg font-black text-accent tracking-tighter">{analysis.vocationalProfile?.marketValueScore}<span className="text-xs">/100</span></span>
                     </div>
                 </div>
                 
                 <div className="bg-accent/5 p-8 rounded-card border-2 border-accent/10">
                    <p className="text-[10px] font-black text-accent uppercase tracking-[0.2em] mb-2">{t.salaryRange}</p>
                    <p className="text-2xl font-black text-text-main tracking-tight">{analysis.vocationalProfile?.salaryRangeEstimation || "N/A"}</p>
                 </div>
             </div>

             {/* CAREER PATHS & GAPS */}
             <div className="md:col-span-2 bg-white rounded-card border-2 border-indigo-50 p-10 shadow-vibrant relative overflow-hidden group">
                 <div className="absolute top-0 right-0 w-1.5 h-full bg-primary/20 group-hover:bg-primary transition-colors"></div>
                 <h3 className="text-xs font-black text-text-muted uppercase tracking-[0.3em] mb-8 flex items-center gap-3">
                    <Briefcase size={20} className="text-primary"/> {t.careerPaths}
                 </h3>
                 <div className="space-y-6">
                    {analysis.careerMatches?.map((match, i) => (
                       <div key={i} className="flex flex-col sm:flex-row gap-6 p-6 hover:bg-indigo-50 rounded-card transition-all border-2 border-transparent hover:border-indigo-100">
                           <div className="flex-1">
                               <div className="flex justify-between items-center mb-2">
                                  <span className="font-black text-text-main text-lg">{match.role}</span>
                                  <span className="text-xs font-black text-primary uppercase tracking-widest bg-indigo-50 px-3 py-1 rounded-pill">{match.matchPercentage}% {t.match}</span>
                               </div>
                               <div className="w-full bg-indigo-100 h-2 rounded-pill mb-4">
                                  <div className="bg-primary h-full rounded-pill shadow-vibrant" style={{width: `${match.matchPercentage}%`}}></div>
                                </div>
                           </div>
                           <div className="flex-1 bg-secondary/5 p-5 rounded-card border border-secondary/10">
                              <p className="text-[10px] font-black text-secondary uppercase tracking-[0.2em] mb-2">{lang === 'en' ? 'Market Alignment' : 'Alineación de Mercado'}</p>
                              <p className="text-xs text-text-main font-bold leading-relaxed">{match.gapAnalysis || "N/A"}</p>
                           </div>
                       </div>
                    ))}
                 </div>
             </div>
          </div>

          {/* SECTION 3: LEARNING PATH */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
             <div className="bg-indigo-50 p-8 rounded-card border-2 border-primary/10">
                 <h3 className="text-xs font-black text-primary uppercase tracking-[0.3em] mb-6 flex items-center gap-3">
                     <BookOpen size={20}/> {t.learningPath}
                 </h3>
                 <ul className="space-y-4">
                     {analysis.vocationalProfile?.recommendedLearningPath?.map((item, i) => (
                         <li key={i} className="flex gap-4 items-start group">
                             <span className="bg-primary text-white w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 text-[10px] font-black mt-0.5 shadow-vibrant group-hover:scale-110 transition-transform">{i+1}</span>
                             <span className="text-sm text-text-main font-bold leading-relaxed">{item}</span>
                         </li>
                     ))}
                 </ul>
             </div>
             
             <div className="bg-amber-50 p-8 rounded-card border-2 border-amber-100">
                 <h3 className="text-xs font-black text-amber-900 uppercase tracking-[0.3em] mb-6 flex items-center gap-3">
                     <TrendingUp size={20}/> {t.topSkills}
                 </h3>
                 <div className="flex flex-wrap gap-3">
                     {analysis.vocationalProfile?.topStrengths?.map((skill, i) => (
                         <span key={i} className="px-4 py-2 bg-white text-amber-900 text-xs font-black rounded-pill border-2 border-amber-200 shadow-sm hover:border-amber-400 transition-colors uppercase tracking-wider">
                             {skill}
                         </span>
                     ))}
                 </div>
                 <div className="mt-8 pt-6 border-t border-amber-200">
                    <div className="bg-white/50 p-4 rounded-xl border border-amber-100">
                       <p className="text-xs text-amber-900 font-bold italic leading-relaxed">
                          "{analysis.performanceEstimate}"
                       </p>
                    </div>
                 </div>
             </div>
          </div>

          {/* FOOTER */}
          <div className="mt-16 pt-8 border-t border-indigo-50 text-center">
             <p className="text-[10px] text-text-muted font-black uppercase tracking-[0.5em]">
                {lang === 'es' ? 'Procedimiento de Auditoría Neural Completado • ATS Master Pro v4.2' : 'Neural Audit Procedure Completed • ATS Master Pro v4.2'}
             </p>
          </div>

      </div>
    </div>
  );
};
